#!/usr/bin/env python3


import os
import sys
import matchmakereft.libs.mm_offline as mm



model_name = os.path.abspath("SMS-stop-v2")
SM_name = os.path.abspath("./MatchMakerEFT/UnbrokenSM_BFM")


# Run feynwrite
#run_and_print(f"feynwrite {particles} > {model_name}.fr")

# Copy generic .symm and .gauge files
#run_and_print(f"cp granada.symm {model_name}.symm")
#run_and_print(f"cp granada.gauge {model_name}.gauge")
#run_and_print(f"cp granada.red {model_name}.red")

# Run Matchmaker
mm.create_model(f"create_model {SM_name}.fr {model_name}.fr")
mm.match_model_to_eft(f"{model_name}_MM SMEFT_Green_Bpreserving_MM")
#mm.compute_rge_model_to_eft(f"{model_name}_MM SMEFT_Green_Bpreserving_MM")


