(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMS-test",
  Authors -> {"Andre Lessa"},
  Version -> "1.0",
  Date -> "18.03.2023"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[6] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "t",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mt },

F[16] == {
    SelfConjugate -> True,
    QuantumNumbers -> {},
    PropagatorLabel -> "chi",
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> mChi,
    Indices -> {} },

S[5] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "ST",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mST }
}


(*        Definitions       *)


mt[ ___ ] := mt;
mChi[ ___ ] := mChi;
mST[ ___ ] := mST;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[6, {__}] ] := TheLabel[F[6]];
TheLabel[ S[5, {__}] ] := TheLabel[S[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}},

C[ S[5, {e1x1}] , -S[5, {e2x1}] ] == {{0, (-I)*FR$deltaZ[{ST, ST}, {{}}]*IndexDelta[e1x1, e2x1]}, {0, (-I)*mST*(2*FR$delta[{mST}, {}] + mST*FR$deltaZ[{ST, ST}, {{}}])*IndexDelta[e1x1, e2x1]}},

C[ F[16] , F[16] ] == {{0, (-I/2)*(FR$deltaZ[{chi, chi}, {{}}, "L"] + FR$deltaZ[{chi, chi}, {{}}, "R"])}, {0, (I/2)*(FR$deltaZ[{chi, chi}, {{}}, "L"] + FR$deltaZ[{chi, chi}, {{}}, "R"])}, {0, (-I/2)*(2*FR$delta[{mChi}, {}] + mChi*FR$deltaZ[{chi, chi}, {{}}, "L"])}, {0, (-I/2)*(2*FR$delta[{mChi}, {}] + mChi*FR$deltaZ[{chi, chi}, {{}}, "R"])}},

C[ -F[6, {e1x2}] , F[6, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{mt}, {}] + mt*FR$deltaZ[{t, t}, {{}}, "L"] + mt*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*(2*FR$delta[{mt}, {}] + mt*FR$deltaZ[{t, t}, {{}}, "L"] + mt*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc6*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc6*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc6*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[6, {e1x2}] , F[16] , S[5, {e3x1}] ] == {{I*gc7*IndexDelta[e1x2, e3x1], (-I/2)*(2*FR$delta[{yDM}, {}] + yDM*FR$deltaZ[{ST, ST}, {{}}] + yDM*FR$deltaZ[{chi, chi}, {{}}, "L"] + yDM*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e3x1]}, {I*gc7*IndexDelta[e1x2, e3x1], (-I/2)*(2*FR$delta[{yDM}, {}] + yDM*FR$deltaZ[{ST, ST}, {{}}] + yDM*FR$deltaZ[{chi, chi}, {{}}, "R"] + yDM*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e3x1]}},

C[ F[16] , F[6, {e2x2}] , -S[5, {e3x1}] ] == {{I*gc8*IndexDelta[e2x2, e3x1], (-I/2)*(2*FR$delta[{yDM}, {}] + yDM*FR$deltaZ[{ST, ST}, {{}}] + yDM*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e2x2, e3x1]}, {I*gc8*IndexDelta[e2x2, e3x1], (-I/2)*(2*FR$delta[{yDM}, {}] + yDM*FR$deltaZ[{ST, ST}, {{}}] + yDM*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e2x2, e3x1]}},

C[ -F[6, {e1x2}] , F[6, {e2x2}] , V[4, {e3x2}] ] == {{I*gc9*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc9*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ S[5, {e2x1}] , -S[5, {e3x1}] , V[4, {e1x2}] ] == {{I*GS*SUNT[e1x2, e3x1, e2x1], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{ST, ST}, {{}}])*SUNT[e1x2, e3x1, e2x1])/aS}},

C[ S[5, {e3x1}] , -S[5, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), (I*GS^2*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + aS*FR$deltaZ[{ST, ST}, {{}}])*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]))/aS}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc6 -> GS^2,
     gc7 -> -yDM,
     gc8 -> -yDM,
     gc9 -> GS};

